version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: t3-solito-postgres
    environment:
      POSTGRES_USER: t3
      POSTGRES_PASSWORD: solito
      POSTGRES_DB: t3-solito
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
