packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@trpc/client': ^11.0.0-rc.660
  '@trpc/server': ^11.0.0-rc.660
  eslint: ^9.12.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.7.2
  zod: ^3.23.8
  prisma: ^6.0.1
  bcrypt: ^5.1.1

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.1
